### ISSUE TITLE
i get an error while importing with a .py file

### ISSUE THREAD

**Issue by jusrose** [audreyfeldroy/standardjson#4]
when i run the file converted to txt provided i get an error looking like this
"
Traceback (most recent call last):
  File "/home/justin/Desktop/pkmn/main.py", line 10, in <module>
    expansion = json.load(expan_list)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
"
[main.txt](https://github.com/audreyr/standardjson/files/3171036/main.txt)

dont know what to make of it

**Comment by jusrose** [comment]
also tried the shell doesn't work there
